### ISSUE TITLE
Section and panels don't have style

### ISSUE THREAD

**Issue by jfcampos1** [cprodhomme/arctic_admin#71]
Hi great project, I really like it.

The section and panels don't have a defined style, and make it difficult to make a nice dashboard.

Maybe you can add or improved the scss on this part, for now I have added custom scss for the panel (from the activeadmin repo)

Here is the scss:

```scss
.panel {
  border: 2px;
  margin: 10px 0;
  border-radius: 3px;
  background-color: whitesmoke;
  box-shadow: inset 0 1px 4px #ddd;

  >h3 {
    background-color: #efefef;
    background-image: linear-gradient(180deg, #efefef, #dfe1e2);
    text-shadow: #fff 0 1px 0;
    border: solid 1px #cdcdcd;
    border-color: #d4d4d4;
    border-top-color: #e6e6e6;
    border-right-color: #d4d4d4;
    border-bottom-color: #cdcdcd;
    border-left-color: #d4d4d4;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 0 1px #fff inset;
    font-size: 1em;
    font-weight: bold;
    line-height: 18px;
    margin-bottom: 0.5em;
    color: #5E6469;
    padding: 5px 10px 3px 10px;
  }

  .panel_contents {
    padding: 10px;
  }
}
```
