### ISSUE TITLE
Active menu expands whole tree

### ISSUE THREAD

**Issue by zorar4ik** [cprodhomme/arctic_admin#78]
https://github.com/cprodhomme/arctic_admin/blob/1d009dcdc87132f5c5875b0b07505a5557bfd3f4/app/assets/stylesheets/arctic_admin/layouts/_sidebar.scss#L98

**Current behaviour:** 
When you have nested menu within your sidebar on click it expands whole tree of childish menus like on image:
![image](https://user-images.githubusercontent.com/22009908/89178859-37226380-d597-11ea-8fc8-db1dbb36e06a.png)

**Expected behaviour:**
By default all nested menus are hidden and open on click only:
![image](https://user-images.githubusercontent.com/22009908/89179089-b1eb7e80-d597-11ea-9775-d6b1b937757b.png)

```css
      &.open, &.current {
        & > a:nth-child(1) {
          position: relative;

          &:after {
            @include icon("\f0d8");
          }
        }

-      ul {
+      & > ul {
          display: block;
        }
      }
```
